name: FSharp Validations CI - Pull Request

on:
  pull_request:
    branches: [main]

permissions:
  checks: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '9.x'

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v3.1.2
      with:
        versionSpec: '6.0.0'

    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v3.1.2
      with:
        useConfigFile: true
    
    - name: Run GitVersion
      run: dotnet gitversion /output buildserver

    - name: Set version
      run: |
        echo "# ${{ env.semVer }}" >> $GITHUB_STEP_SUMMARY

    - name: Restore dependencies
      run: dotnet restore src/

    - name: Build
      run: dotnet build src/ -c Release --no-restore
